version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3360:3306"
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel_redis
    networks:
      - laravel
    ports:
      - "6380:6379"

  memcached:
    image: memcached:latest
    container_name: laravel_memcached
    networks:
      - laravel
    ports:
      - "11211:11211"

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
